name: run-macos-matrix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14, macos-latest]
      fail-fast: false
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3

     -  shell: pwsh
        run: |
          $guestMacosVersion = sw_vers
          Write-Host $guestMacosVersion
          switch -regex ($guestMacosVersion[1]) {
              '12.\d' { $nextOSVersion = 'macOS Ventura|macOS Sonoma|macOS Sequoia' }
              '13.\d' { $nextOSVersion = 'macOS Sonoma|macOS Sequoia' }
              '14.\d' { $nextOSVersion = 'macOS Sequoia' }
          }
          Write-Host "nextOSVersion var = $nextOSVersion"
          Write-Host "========="
          $updates = /usr/sbin/softwareupdate --list
          $updates = $updates | Where-Object { $_ -match "(Label|Title):" } | Out-String
          Write-Host "updates var type = $($updates.gettype())"
          Write-Host "updates var = $updates"
          Write-Host "========="
          $listOfNewUpdates = $($($updates.Split("*")).Split("Title").where({$_ -match "Label:"}).Replace("Label: ", '').where({$_ -notmatch $nextOSVersion}))
          Write-Host $listOfNewUpdates
          Write-Host "listOfNewUpdates var type = $($listOfNewUpdates.gettype())"
      # - run: |
      #     download_path="/tmp/MonoFramework-MDK-6.12.0.188.macos10.xamarin.universal.pkg"
      #     url="https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.188.macos10.xamarin.universal.pkg"
      #     curl -4sSLo "$download_path" "$url" -w '%{http_code}'

      # - run: xcode-select -p

      # - run: ls -la /Library/Developer/CommandLineTools/SDKs

      # - run: xcrun --show-sdk-version

      # - name: Print env vars
      #   shell: pwsh
      #   run: 
      #     Get-ChildItem env:\

      # - run: echo $PATH

      # - run: |
      #     nslookup keyserver.ubuntu.com
      #     echo "=============="
      #     dscacheutil -q host -a name keyserver.ubuntu.com

      # - run: |
      #     ps -ax | fgrep -i mdns

      # - run: |
      #     brew update
      #     brew upgrade xz

      # - run: |
      #     xz -V
      #     which xz
      # - run: npm install
      # - run: |
      #     clt_placeholder="/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
      #     sudo touch $clt_placeholder
          
      #     /usr/sbin/softwareupdate -l

      # - shell: pwsh
      #   run: |
      #     function Run-Command {
      #         param (
      #             [Parameter(Mandatory=$true)]
      #             [string] $Command,
      #             [switch] $SuppressStderr
      #         )
      #         # Bash trick to suppress and show error output because some commands write to stderr (for example, "python --version")
      #         $redirectOutputArguments = If ($SuppressStderr) { "2> /dev/null" } Else { "2>&1" }
      #         $stdout = & bash -c "${Command} ${redirectOutputArguments}"
          
      #         return $stdout
      #     }

      #     function Take-Part {
      #         param (
      #             [Parameter(ValueFromPipeline)]
      #             [string] $toolOutput,
      #             [string] $Delimiter = " ",
      #             [int[]] $Part
      #         )
      #         $parts = $toolOutput.Split($Delimiter, [System.StringSplitOptions]::RemoveEmptyEntries)
      #         $selectedParts = $parts[$Part]
      #         return [string]::Join($Delimiter, $selectedParts)
      #     }
          
      #     "Run-Command composer --version"
      #     Run-Command "composer --version"
          
      #     "Run-Command composer --version | Take-Part -Part 2" 
      #     Run-Command "composer --version" | Take-Part -Part 2
          
      #     "Run-Command composer --version | Select-Object -First 1 | Take-Part -Part 2" 
      #     Run-Command "composer --version" | Select-Object -First 1 | Take-Part -Part 2
