name: test-python-ios
# https://github.com/actions/runner-images/issues/13228

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  build-ios:
    name: iOS
    timeout-minutes: 60
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'python/cpython'
          persist-credentials: false

      # GitHub recommends explicitly selecting the desired Xcode version:
      # https://github.com/actions/runner-images/issues/12541#issuecomment-3083850140
      # This became a necessity as a result of
      # https://github.com/actions/runner-images/issues/12541 and
      # https://github.com/actions/runner-images/issues/12751.
      - name: Select Xcode version
        run: |
          sudo xcode-select --switch /Applications/Xcode_16.4.app

      - name: Build and test
        run: python3 Apple ci iOS --fast-ci --simulator 'iPhone 16e,OS=18.5'
