name: test-ubuntu-java-25
# https://github.com/actions/setup-java/issues/933
on:
  # push:
  #   branches:
  #     - '*'
  #     - '!master'
  workflow_dispatch:

jobs:
  linux_build_parallel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: 'sblantipodi/firefly_luciferin'
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Release version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: debug
        run: |
          sudo rm -rf /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/25.0.0-36
          ls -la /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk
      - name: Set up AdoptOpenJDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          architecture: x64
      - id: get-id
        run: |
          id=$(grep -oPm1 "(?<=<version>)[^<]+" "pom.xml")
          echo "id=$id" >> $GITHUB_OUTPUT
      #       - name: Setup tmate session
      #         uses: mxschmitt/action-tmate@v3
      - name: Publish package
        run: |
          mvn -B package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Java 14 Package API, create Linux binary
        run: |
          ls -la target
          rm -rf target/fireflyluciferin-${{steps.get-id.outputs.id}}.jar;
          jpackage -i target --main-class org.dpsoftware.JavaFXStarter --main-jar FireflyLuciferin-jar-with-dependencies.jar --icon data/img/luciferin_logo.png --linux-shortcut --copyright "Davide Perini" --name FireflyLuciferin  --vendor DPsoftware --app-version "${{steps.get-id.outputs.id}}" --java-options "-XX:+UseZGC -XX:+UseStringDeduplication -Xms64m -Xmx1024m --add-modules=jdk.incubator.vector --enable-native-access=org.dpsoftware --enable-native-access=ALL-UNNAMED --enable-native-access=com.sun.jna --enable-native-access=javafx.graphics --enable-native-access=javafx.web --enable-native-access=com.fazecast.jSerialComm --enable-native-access=org.newsclub.net.unix"
      - name: Adding Linux asset to the release (Debian flavour)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv firefly* FireflyLuciferinLinux.deb;
      - name: Deps fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dpkg-deb -R FireflyLuciferinLinux.deb firetoedit
          sed -i 's/libasound2t64/libasound2/g' "firetoedit/DEBIAN/control"
          sed -i 's/Unknown/perini.davide@dpsoftware.org/g' "firetoedit/DEBIAN/control"
          dpkg-deb -b firetoedit FireflyLuciferinLinux.deb
          cat firetoedit/DEBIAN/control
          rm -rf firetoedit
      - name: Creating artifact from BIN file
        uses: actions/upload-artifact@v4
        with:
          name: FireflyLuciferinLinux_${{steps.get-id.outputs.id}}_ALPHA.deb
          path: FireflyLuciferinLinux.deb
      - name: Adding Linux asset to the release (RedHat flavour)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt install alien -y;
          sudo alien -r FireflyLuciferinLinux.deb
          mv *.rpm FireflyLuciferinLinux.rpm;
      - name: Creating artifact from BIN file
        uses: actions/upload-artifact@v4
        with:
          name: FireflyLuciferinLinux_${{steps.get-id.outputs.id}}_ALPHA.rpm
          path: FireflyLuciferinLinux.rpm
#      - name: Setup action-debug-vscode session
#        uses: fawazahmed0/action-debug-vscode@main
