name: test-environments

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

  update-1:
    name: Test 1
    needs: [deploy]
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
    with:
      arg1: 'arg1'
      arg2: 'arg2'
      arg3: 'arg3'

  update-2:
    name: Test 2
    needs: [update-1]
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
    with:
      arg1: 'arg1'
      arg2: 'arg2'
      arg3: 'arg3'

  update-3:
    name: Test 3
    needs: [update-2]
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
    with:
      arg1: 'arg1'
      arg2: 'arg2'
      arg3: 'arg3'

# V2
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     environment: deploy
#     steps:
#       - uses: actions/checkout@v4

#       - name: Run a one-line script
#         run: echo Hello, world!

#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.

#   rollback:

#     runs-on: ubuntu-latest
#     needs: deploy
#     environment: deploy

#     steps:
#       - uses: actions/checkout@v4

#       - name: Run a one-line script
#         run: echo Hello, world!

#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
